// NurseDashboard.tsx — WardWatch v3 | Enhanced Nurse Workflow System
// ─────────────────────────────────────────────────────────────────────
// Features: Sidebar, Header, ECG Monitors, Shift Handover, Full Escalation,
// Real-time Vital Fluctuations, Priority Assignments, Task Intelligence Levels,
// Auto Task Regeneration, Patient History Snapshot, Real-time Alerts & Risk Prediction

import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { api } from "@/lib/api";
import {
  Heart, Activity, Wind, AlertTriangle, CheckCircle2, Clock, Bell,
  Phone, ClipboardList, User, Thermometer, Zap, RefreshCw, Filter,
  ShieldAlert, ChevronRight, ChevronLeft, LayoutDashboard, Users,
  FileText, Settings, LogOut, Menu, X, TrendingUp, TrendingDown,
  Minus, Brain, ArrowUpCircle, Siren, History, BarChart3,
  Stethoscope, CalendarClock, UserCheck, AlertCircle, Shield,
  Layers, TriangleAlert, Flame, Star, BookOpen,
} from "lucide-react";

// ─── Variants ────────────────────────────────────────────────────────────────
const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.05, delayChildren: 0.1 } },
};
const itemVariants = {
  hidden: { opacity: 0, y: 10 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.4 } },
};
const slideIn = {
  hidden: { opacity: 0, x: -20 },
  visible: { opacity: 1, x: 0, transition: { duration: 0.3 } },
};

// ─── Types ────────────────────────────────────────────────────────────────────
type Severity = "critical" | "moderate" | "stable";
type TaskStatus = "pending" | "completed" | "overdue";
type TaskIntelligence = "routine" | "advisory" | "urgent" | "emergency";
type Priority = "P1" | "P2" | "P3" | "P4";
type SidebarView = "overview" | "patients" | "handover" | "escalation" | "alerts" | "history" | "analytics";
type EscalationLevel = 1 | 2 | 3 | 4 | 5;

interface Vitals {
  heartRate: number;
  oxygen: number;
  bpSystolic: number;
  bpDiastolic: number;
  temperature: number;
  respiratoryRate: number;
  lastChecked: number;
  ecgPoints?: number[];
}

interface VitalTrend {
  timestamp: number;
  heartRate: number;
  oxygen: number;
  bpSystolic: number;
}

interface NurseTask {
  id: string;
  patientId: string;
  label: string;
  status: TaskStatus;
  assignedAt: number;
  completedAt?: number;
  dueDuration: number;
  intelligence: TaskIntelligence;
  priority: Priority;
  autoGenerated?: boolean;
  reasoning?: string;
}

interface PatientHistoryEvent {
  timestamp: number;
  type: "vitals" | "task" | "medication" | "doctor" | "alert" | "admission";
  description: string;
  severity?: Severity;
}

interface NursePatient {
  id: string;
  name: string;
  age: number;
  ward: string;
  bed: string;
  disease: string;
  severity: Severity;
  vitals: Vitals;
  vitalHistory: VitalTrend[];
  tasks: NurseTask[];
  flagged: boolean;
  priority: Priority;
  riskScore: number;
  riskFactors: string[];
  escalationLevel: EscalationLevel;
  assignedNurse: string;
  admittedAt: number;
  history: PatientHistoryEvent[];
  allergies: string[];
  medications: string[];
  notes: string;
}

interface ShiftHandover {
  id: string;
  fromNurse: string;
  toNurse: string;
  shiftEnd: string;
  summary: string;
  criticalNotes: string[];
  pendingTasks: string[];
  completedAt?: number;
  status: "pending" | "completed" | "in-progress";
}

interface EscalationRecord {
  id: string;
  patientId: string;
  patientName: string;
  level: EscalationLevel;
  reason: string;
  initiatedAt: number;
  respondedAt?: number;
  status: "open" | "acknowledged" | "resolved";
  assignedTo?: string;
}

interface RealTimeAlert {
  id: string;
  patientId?: string;
  patientName?: string;
  type: "vitals" | "task" | "escalation" | "system" | "risk";
  message: string;
  severity: Severity;
  timestamp: number;
  acknowledged: boolean;
}

interface NurseDashboardProps {
  nurseName?: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function uid() { return Math.random().toString(36).slice(2, 9); }
function formatTime(ts: number) {
  return new Date(ts).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}
function formatElapsed(ts: number): string {
  const ms = Date.now() - ts;
  const mins = Math.floor(ms / 60000);
  if (mins < 60) return `${mins}m ago`;
  return `${Math.floor(mins / 60)}h ${mins % 60}m ago`;
}
function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString("en-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" });
}
function isVitalAbnormal(v: Vitals): boolean {
  return v.oxygen < 92 || v.heartRate > 110 || v.heartRate < 50 || v.temperature > 38.5 ||
    v.bpSystolic > 160 || v.respiratoryRate > 22;
}

function computeRiskScore(v: Vitals, severity: Severity): number {
  let score = 0;
  if (severity === "critical") score += 40;
  else if (severity === "moderate") score += 20;
  if (v.oxygen < 88) score += 25;
  else if (v.oxygen < 92) score += 15;
  if (v.heartRate > 130 || v.heartRate < 45) score += 20;
  else if (v.heartRate > 110 || v.heartRate < 55) score += 10;
  if (v.bpSystolic > 180) score += 15;
  if (v.temperature > 39.5) score += 15;
  if (v.respiratoryRate > 25) score += 10;
  return Math.min(100, score);
}

function computeRiskFactors(v: Vitals, severity: Severity, disease: string): string[] {
  const factors: string[] = [];
  if (v.oxygen < 92) factors.push("Hypoxemia");
  if (v.heartRate > 110) factors.push("Tachycardia");
  if (v.heartRate < 50) factors.push("Bradycardia");
  if (v.bpSystolic > 160) factors.push("Hypertensive crisis");
  if (v.temperature > 38.5) factors.push("Fever");
  if (v.respiratoryRate > 22) factors.push("Tachypnea");
  if (severity === "critical") factors.push("Critical diagnosis");
  if (disease.toLowerCase().includes("septic")) factors.push("Sepsis risk");
  if (disease.toLowerCase().includes("cardiac") || disease.toLowerCase().includes("stemi")) factors.push("Cardiac event");
  return factors;
}

function computeEscalationLevel(riskScore: number, severity: Severity): EscalationLevel {
  if (riskScore >= 80 || severity === "critical") return 5;
  if (riskScore >= 60) return 4;
  if (riskScore >= 40) return 3;
  if (riskScore >= 20) return 2;
  return 1;
}

function getTaskIntelligence(label: string, priority: Priority): TaskIntelligence {
  if (label.includes("⚠") || label.includes("immediate") || priority === "P1") return "emergency";
  if (label.includes("critical") || label.includes("doctor") || priority === "P2") return "urgent";
  if (label.includes("monitor") || label.includes("update")) return "advisory";
  return "routine";
}

function generateEcgPoints(heartRate: number, abnormal: boolean): number[] {
  const points: number[] = [];
  const cycles = 6;
  const perCycle = 20;
  for (let c = 0; c < cycles; c++) {
    for (let i = 0; i < perCycle; i++) {
      const x = i / perCycle;
      let y = 0;
      if (x < 0.1) y = 0;
      else if (x < 0.15) y = abnormal ? -8 + Math.random() * 4 : -3;
      else if (x < 0.2) y = abnormal ? -4 + Math.random() * 3 : -1;
      else if (x < 0.25) y = 0;
      else if (x < 0.3) y = abnormal ? 28 + Math.random() * 12 : 18;
      else if (x < 0.35) y = abnormal ? -15 + Math.random() * 8 : -10;
      else if (x < 0.4) y = abnormal ? 8 + Math.random() * 5 : 5;
      else if (x < 0.45) y = 0;
      else if (x < 0.6) y = abnormal ? 5 + Math.sin(x * 40) * 3 : 3;
      else if (x < 0.7) y = 0;
      else y = abnormal ? Math.random() * 2 - 1 : 0;
      points.push(y);
    }
  }
  return points;
}

function generateVitalsForSeverity(severity: Severity): Vitals {
  const base = {
    stable: { hr: () => 65 + Math.random() * 20, o2: () => 96 + Math.random() * 3, bpS: () => 115 + Math.random() * 15, bpD: () => 70 + Math.random() * 10, temp: () => 36.5 + Math.random() * 0.5, rr: () => 14 + Math.random() * 4 },
    moderate: { hr: () => 90 + Math.random() * 20, o2: () => 92 + Math.random() * 5, bpS: () => 130 + Math.random() * 20, bpD: () => 80 + Math.random() * 15, temp: () => 37.5 + Math.random() * 0.8, rr: () => 18 + Math.random() * 5 },
    critical: { hr: () => 108 + Math.random() * 30, o2: () => 84 + Math.random() * 10, bpS: () => 150 + Math.random() * 30, bpD: () => 95 + Math.random() * 20, temp: () => 38.8 + Math.random() * 1.2, rr: () => 22 + Math.random() * 8 },
  }[severity];
  const hr = Math.round(base.hr());
  const o2 = Math.round(base.o2());
  const abnormal = o2 < 92 || hr > 110;
  return {
    heartRate: hr, oxygen: o2, bpSystolic: Math.round(base.bpS()),
    bpDiastolic: Math.round(base.bpD()), temperature: parseFloat(base.temp().toFixed(1)),
    respiratoryRate: Math.round(base.rr()), lastChecked: Date.now() - Math.floor(Math.random() * 90 * 60 * 1000),
    ecgPoints: generateEcgPoints(hr, abnormal),
  };
}

function generateVitalHistory(severity: Severity): VitalTrend[] {
  const now = Date.now();
  return Array.from({ length: 8 }, (_, i) => {
    const v = generateVitalsForSeverity(severity);
    return { timestamp: now - (7 - i) * 30 * 60 * 1000, heartRate: v.heartRate, oxygen: v.oxygen, bpSystolic: v.bpSystolic };
  });
}

function generateHistory(patientId: string, disease: string): PatientHistoryEvent[] {
  const now = Date.now();
  return [
    { timestamp: now - 6 * 60 * 60 * 1000, type: "admission", description: `Admitted with ${disease}`, severity: "critical" },
    { timestamp: now - 5 * 60 * 60 * 1000, type: "doctor", description: "Dr. Sharma evaluated — treatment plan initiated" },
    { timestamp: now - 4 * 60 * 60 * 1000, type: "medication", description: "IV antibiotics administered — ceftriaxone 2g" },
    { timestamp: now - 3 * 60 * 60 * 1000, type: "vitals", description: "Vitals check — slight improvement noted", severity: "moderate" },
    { timestamp: now - 2 * 60 * 60 * 1000, type: "task", description: "Patient repositioned — pressure sore prevention" },
    { timestamp: now - 60 * 60 * 1000, type: "alert", description: "SpO₂ dropped briefly — supplemental O₂ applied", severity: "moderate" },
    { timestamp: now - 30 * 60 * 1000, type: "vitals", description: "Routine vitals check completed" },
  ];
}

function generateTasksForSeverity(patientId: string, severity: Severity, abnormalVitals: boolean): NurseTask[] {
  const now = Date.now();
  const tasks: NurseTask[] = [];

  const makeTask = (label: string, due: number, priority: Priority, reasoning?: string): NurseTask => ({
    id: uid(), patientId, label, status: "pending", assignedAt: now, dueDuration: due,
    intelligence: getTaskIntelligence(label, priority), priority, reasoning,
  });

  if (severity === "critical") {
    tasks.push(makeTask("Check vitals immediately", 10 * 60 * 1000, "P1", "Critical patient requires immediate vital assessment"));
    tasks.push(makeTask("Notify attending doctor", 5 * 60 * 1000, "P1", "Medical oversight required for critical status"));
    tasks.push(makeTask("Administer IV medication", 15 * 60 * 1000, "P1", "Time-sensitive pharmacological intervention"));
    tasks.push(makeTask("Document critical event", 20 * 60 * 1000, "P2", "Compliance and handover documentation"));
    tasks.push(makeTask("Prepare emergency cart nearby", 30 * 60 * 1000, "P2", "Precautionary readiness for deterioration"));
  } else if (severity === "moderate") {
    tasks.push(makeTask("Monitor vitals every hour", 60 * 60 * 1000, "P2", "Trending required for moderate stability"));
    tasks.push(makeTask("Administer scheduled medication", 30 * 60 * 1000, "P2", "Per care plan protocol"));
    tasks.push(makeTask("Update patient chart", 90 * 60 * 1000, "P3", "Documentation for clinical continuity"));
    tasks.push(makeTask("Physiotherapy assessment", 2 * 60 * 60 * 1000, "P3", "Mobility and recovery assessment"));
  } else {
    tasks.push(makeTask("Routine vitals check", 4 * 60 * 60 * 1000, "P3", "Standard monitoring for stable patients"));
    tasks.push(makeTask("Patient comfort assessment", 6 * 60 * 60 * 1000, "P4", "Quality of care — pain, comfort, needs"));
    tasks.push(makeTask("Update discharge notes", 8 * 60 * 60 * 1000, "P4", "Preparation for potential discharge"));
  }

  if (abnormalVitals) {
    tasks.unshift(makeTask("⚠ Abnormal vitals — immediate review", 5 * 60 * 1000, "P1", "AI flagged: vitals outside safe range — auto-generated"));
    tasks[0].autoGenerated = true;
  }

  return tasks;
}

// ─── Demo Data ────────────────────────────────────────────────────────────────
const NURSES = ["Nurse Deepa", "Nurse Prashant", "Nurse Lalitha", "Nurse Firoz", "Nurse Rekha"];

const DEMO_PATIENTS_RAW = [
  { id: "p1", name: "Priya Sharma", age: 54, ward: "ICU", bed: "B-01", disease: "Septic Shock", severity: "critical" as Severity, allergies: ["Penicillin"], medications: ["Norepinephrine", "Meropenem", "Vasopressin"], notes: "Admitted from ER. Sepsis secondary to UTI. ICU monitoring ongoing." },
  { id: "p2", name: "Rohan Mehta", age: 67, ward: "Cardiology", bed: "C-03", disease: "STEMI Recovery", severity: "critical" as Severity, allergies: ["Aspirin (mild)"], medications: ["Heparin", "Clopidogrel", "Metoprolol"], notes: "Post-catheterization. Stent placed LAD. Close cardiac monitoring." },
  { id: "p3", name: "Ananya Patel", age: 34, ward: "General Ward A", bed: "G-07", disease: "Dengue Hemorrhagic", severity: "moderate" as Severity, allergies: [], medications: ["Paracetamol", "IV fluids"], notes: "Platelet count monitoring. Dengue NS1 positive." },
  { id: "p4", name: "Vikram Singh", age: 72, ward: "Orthopaedics", bed: "O-02", disease: "Hip Replacement", severity: "moderate" as Severity, allergies: ["Codeine"], medications: ["Enoxaparin", "Paracetamol", "Tramadol"], notes: "Post-op day 2. DVT prophylaxis active. Physio commenced." },
  { id: "p5", name: "Meera Iyer", age: 28, ward: "Maternity", bed: "M-05", disease: "Pre-eclampsia", severity: "moderate" as Severity, allergies: [], medications: ["Labetalol", "MgSO4", "Betamethasone"], notes: "32 weeks gestation. BP management. Fetal monitoring q4h." },
  { id: "p6", name: "Arjun Reddy", age: 45, ward: "General Ward A", bed: "G-12", disease: "Typhoid Fever", severity: "stable" as Severity, allergies: [], medications: ["Ciprofloxacin", "IV fluids"], notes: "Day 4 of antibiotics. Improving appetite. Temperature trending down." },
  { id: "p7", name: "Kavya Nair", age: 8, ward: "Pediatrics", bed: "P-03", disease: "Febrile Seizures", severity: "stable" as Severity, allergies: ["Ibuprofen"], medications: ["Paracetamol", "Diazepam PRN"], notes: "Post-seizure monitoring. Parents present. EEG scheduled tomorrow." },
  { id: "p8", name: "Suresh Gupta", age: 61, ward: "Cardiology", bed: "C-08", disease: "Atrial Fibrillation", severity: "moderate" as Severity, allergies: [], medications: ["Digoxin", "Warfarin", "Bisoprolol"], notes: "Rate controlled. INR monitoring daily. Cardiology review tomorrow." },
];

function buildPatients(): NursePatient[] {
  return DEMO_PATIENTS_RAW.map((p, i) => {
    const vitals = generateVitalsForSeverity(p.severity);
    const abnormal = isVitalAbnormal(vitals);
    const riskScore = computeRiskScore(vitals, p.severity);
    return {
      ...p, vitals, flagged: abnormal,
      vitalHistory: generateVitalHistory(p.severity),
      tasks: generateTasksForSeverity(p.id, p.severity, abnormal),
      priority: p.severity === "critical" ? "P1" : p.severity === "moderate" ? "P2" : "P3" as Priority,
      riskScore,
      riskFactors: computeRiskFactors(vitals, p.severity, p.disease),
      escalationLevel: computeEscalationLevel(riskScore, p.severity) as EscalationLevel,
      assignedNurse: NURSES[i % NURSES.length],
      admittedAt: Date.now() - Math.random() * 3 * 24 * 60 * 60 * 1000,
      history: generateHistory(p.id, p.disease),
    };
  }).sort((a, b) => {
    const order: Record<Severity, number> = { critical: 0, moderate: 1, stable: 2 };
    if (a.flagged !== b.flagged) return a.flagged ? -1 : 1;
    return order[a.severity] - order[b.severity];
  });
}

function buildHandovers(): ShiftHandover[] {
  return [
    {
      id: uid(), fromNurse: "Nurse Deepa", toNurse: "Nurse Prashant", shiftEnd: "14:00",
      summary: "Morning shift — 2 critical patients in ICU and Cardiology require close monitoring. Priya Sharma's MAP trending low, escalated to Dr. Subramaniam at 12:30.",
      criticalNotes: ["Priya Sharma (B-01): Vasopressor dose increased at 11:45", "Rohan Mehta (C-03): Post-cath watch — no bleeding so far", "Meera Iyer (M-05): BP spike at 13:00 — Labetalol given"],
      pendingTasks: ["Priya Sharma: 14:00 vitals check", "Kavya Nair: EEG consent form pending", "Suresh Gupta: INR result collection at 15:00"],
      status: "in-progress",
    },
    {
      id: uid(), fromNurse: "Nurse Rekha", toNurse: "Nurse Lalitha", shiftEnd: "22:00",
      summary: "Evening handover. ICU stable as of 21:45. No new admissions. Typhoid patient (G-12) tolerating oral feeds.",
      criticalNotes: ["All critical patients reviewed by on-call doctor at 20:00", "Ananya Patel: platelets at 68k — watch for bleeding signs"],
      pendingTasks: ["Night vitals round at 00:00", "Priya Sharma: vancomycin levels morning"],
      status: "pending",
    },
  ];
}

function buildEscalations(patients: NursePatient[]): EscalationRecord[] {
  return patients.filter(p => p.escalationLevel >= 4).map(p => ({
    id: uid(), patientId: p.id, patientName: p.name, level: p.escalationLevel,
    reason: p.riskFactors.join(", ") || "Critical vitals",
    initiatedAt: Date.now() - Math.random() * 30 * 60 * 1000,
    status: p.escalationLevel === 5 ? "open" : "acknowledged",
    assignedTo: "Dr. Subramaniam",
  }));
}

function buildAlerts(patients: NursePatient[]): RealTimeAlert[] {
  const alerts: RealTimeAlert[] = [];
  patients.forEach(p => {
    if (p.vitals.oxygen < 90) alerts.push({ id: uid(), patientId: p.id, patientName: p.name, type: "vitals", message: `SpO₂ critically low at ${p.vitals.oxygen}%`, severity: "critical", timestamp: Date.now() - Math.random() * 5 * 60 * 1000, acknowledged: false });
    if (p.vitals.heartRate > 130) alerts.push({ id: uid(), patientId: p.id, patientName: p.name, type: "vitals", message: `Heart rate at ${p.vitals.heartRate} bpm — severe tachycardia`, severity: "critical", timestamp: Date.now() - Math.random() * 10 * 60 * 1000, acknowledged: false });
    if (p.riskScore >= 70) alerts.push({ id: uid(), patientId: p.id, patientName: p.name, type: "risk", message: `Risk score ${p.riskScore}/100 — deterioration likely`, severity: "critical", timestamp: Date.now() - Math.random() * 15 * 60 * 1000, acknowledged: p.riskScore < 80 });
  });
  alerts.push({ id: uid(), type: "system", message: "Shift handover due in 45 minutes", severity: "moderate", timestamp: Date.now() - 5 * 60 * 1000, acknowledged: false });
  return alerts;
}

// ─── Sub-components ───────────────────────────────────────────────────────────

// ECG Monitor
function ECGMonitor({ patient }: { patient: NursePatient }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const posRef = useRef(0);
  const pointsRef = useRef<number[]>(patient.vitals.ecgPoints || []);
  const abnormal = isVitalAbnormal(patient.vitals);
  const color = abnormal ? "#ef4444" : "#22c55e";

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const W = canvas.width, H = canvas.height;
    const midY = H / 2;
    const pts = pointsRef.current;
    let frame = 0;
    let animId: number;
    const draw = () => {
      ctx.fillStyle = "rgba(0,0,0,0.15)";
      ctx.fillRect(0, 0, W, H);
      const visibleW = 4;
      ctx.clearRect(posRef.current * (W / pts.length) - visibleW, 0, visibleW + 2, H);
      const idx = posRef.current % pts.length;
      const x = (posRef.current % pts.length) * (W / pts.length);
      const prevIdx = (idx - 1 + pts.length) % pts.length;
      const prevX = prevIdx * (W / pts.length);
      const y = midY - pts[idx] * (midY / 30);
      const prevY = midY - pts[prevIdx] * (midY / 30);
      ctx.beginPath();
      ctx.moveTo(prevX, prevY);
      ctx.lineTo(x, y);
      ctx.strokeStyle = color;
      ctx.lineWidth = 1.5;
      ctx.shadowColor = color;
      ctx.shadowBlur = abnormal ? 6 : 3;
      ctx.stroke();
      posRef.current = (posRef.current + 1) % pts.length;
      frame++;
      animId = requestAnimationFrame(draw);
    };
    animId = requestAnimationFrame(draw);
    return () => cancelAnimationFrame(animId);
  }, [patient.id, color, abnormal]);

  return (
    <div className={`rounded-2xl overflow-hidden border ${abnormal ? "border-red-400/50 bg-black/80" : "border-green-400/30 bg-black/70"}`}>
      <div className="flex items-center justify-between px-3 py-1.5">
        <div className="flex items-center gap-1.5">
          <Activity className={`w-3 h-3 ${abnormal ? "text-red-400" : "text-green-400"}`} />
          <span className={`text-xs font-mono font-bold ${abnormal ? "text-red-400" : "text-green-400"}`}>
            ECG · {patient.vitals.heartRate} bpm
          </span>
        </div>
        {abnormal && (
          <span className="text-xs text-red-400 font-bold animate-pulse">ABNORMAL</span>
        )}
      </div>
      <canvas ref={canvasRef} width={340} height={56} className="w-full" style={{ imageRendering: "pixelated" }} />
    </div>
  );
}

// VitalBadge
function VitalBadge({ icon, label, value, abnormal, trend }: { icon: React.ReactNode; label: string; value: string; abnormal: boolean; trend?: "up" | "down" | "stable" }) {
  return (
    <div className={`flex flex-col items-center p-3 rounded-2xl border text-xs transition-all ${abnormal ? "bg-red-50 border-red-300 text-red-700 shadow-sm shadow-red-100" : "bg-white/40 border-white/40 text-gray-600"}`}>
      <div className="flex items-center gap-1 mb-1">
        <span className={abnormal ? "text-red-500" : "text-gray-400"}>{icon}</span>
        {trend === "up" && <TrendingUp className="w-3 h-3 text-red-400" />}
        {trend === "down" && <TrendingDown className="w-3 h-3 text-blue-400" />}
        {trend === "stable" && <Minus className="w-3 h-3 text-gray-400" />}
      </div>
      <span className="font-bold text-sm">{value}</span>
      <span className="text-xs opacity-70">{label}</span>
    </div>
  );
}

// Risk Score Ring
function RiskRing({ score, size = 64 }: { score: number; size?: number }) {
  const r = size / 2 - 6;
  const circ = 2 * Math.PI * r;
  const filled = (score / 100) * circ;
  const color = score >= 70 ? "#ef4444" : score >= 40 ? "#f59e0b" : "#22c55e";
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="#e5e7eb" strokeWidth={5} />
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={color} strokeWidth={5}
        strokeDasharray={`${filled} ${circ - filled}`} strokeLinecap="round"
        transform={`rotate(-90 ${size / 2} ${size / 2})`} />
      <text x="50%" y="50%" dominantBaseline="middle" textAnchor="middle" fontSize={size * 0.22} fontWeight="bold" fill={color}>{score}</text>
    </svg>
  );
}

// TaskRow
function TaskRow({ task, onComplete }: { task: NurseTask; onComplete: (id: string) => void }) {
  const now = Date.now();
  const overdueMs = now - task.assignedAt - task.dueDuration;
  const isOverdue = task.status === "pending" && overdueMs > 0;

  const intelColors: Record<TaskIntelligence, string> = {
    emergency: "bg-red-500 text-white",
    urgent: "bg-orange-500 text-white",
    advisory: "bg-blue-500 text-white",
    routine: "bg-gray-400 text-white",
  };
  const priorityColors: Record<Priority, string> = {
    P1: "text-red-600 font-bold", P2: "text-orange-500 font-semibold", P3: "text-blue-500", P4: "text-gray-400",
  };

  return (
    <motion.div layout initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}
      className={`flex items-start gap-2 p-2.5 rounded-xl border transition-all ${task.status === "completed" ? "bg-green-50 border-green-200 opacity-70" : isOverdue ? "bg-red-50 border-red-300" : "bg-white/30 border-white/40"}`}>
      <button onClick={() => task.status === "pending" && onComplete(task.id)}
        className={`mt-0.5 w-5 h-5 rounded-full border-2 flex-shrink-0 flex items-center justify-center transition-all ${task.status === "completed" ? "bg-green-500 border-green-500 text-white" : isOverdue ? "border-red-400 hover:bg-red-100" : "border-gray-300 hover:bg-blue-50 hover:border-blue-400"}`}>
        {task.status === "completed" && <svg viewBox="0 0 10 10" className="w-3 h-3" fill="none" stroke="white" strokeWidth="2"><path d="M2 5l2.5 2.5L8 3" /></svg>}
      </button>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5 flex-wrap">
          <span className={`text-xs px-1.5 py-0.5 rounded-full ${intelColors[task.intelligence]}`} style={{ fontSize: "10px" }}>{task.intelligence.toUpperCase()}</span>
          <span className={`text-xs ${priorityColors[task.priority]}`}>{task.priority}</span>
          {task.autoGenerated && <span className="text-xs text-purple-600" style={{ fontSize: "10px" }}>⚡AUTO</span>}
        </div>
        <p className={`text-xs font-medium leading-tight mt-0.5 ${task.status === "completed" ? "line-through text-gray-400" : isOverdue ? "text-red-700" : "text-gray-700"}`}>{task.label}</p>
        {task.reasoning && <p className="text-xs text-gray-400 mt-0.5 leading-tight italic">{task.reasoning}</p>}
        <p className="text-xs mt-0.5 text-gray-400">
          {task.status === "completed" && task.completedAt ? `✓ Done ${formatTime(task.completedAt)}` : isOverdue ? `⚠ Overdue ${Math.floor(overdueMs / 60000)}m` : `Due in ${Math.max(0, Math.floor((task.assignedAt + task.dueDuration - now) / 60000))}m`}
        </p>
      </div>
    </motion.div>
  );
}

// PatientCard
function PatientCard({ patient, selected, onSelect }: { patient: NursePatient; selected: boolean; onSelect: () => void }) {
  const pendingCount = patient.tasks.filter(t => t.status === "pending").length;
  const overdueCount = patient.tasks.filter(t => t.status === "pending" && Date.now() - t.assignedAt - t.dueDuration > 0).length;
  const priorityColors: Record<Priority, string> = { P1: "text-red-600 bg-red-100", P2: "text-orange-500 bg-orange-100", P3: "text-blue-500 bg-blue-100", P4: "text-gray-400 bg-gray-100" };

  return (
    <motion.div variants={itemVariants} whileHover={{ scale: 1.01 }} onClick={onSelect}
      className={`glass p-4 rounded-2xl border cursor-pointer transition-all ${selected ? "border-blue-400 shadow-lg shadow-blue-100" : patient.flagged ? "border-red-300 shadow-sm shadow-red-100" : "border-white/40"}`}>
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${patient.severity === "critical" ? "bg-red-100 text-red-600" : patient.severity === "moderate" ? "bg-amber-100 text-amber-600" : "bg-green-100 text-green-600"}`}>
            {patient.name[0]}
          </div>
          <div>
            <p className="font-semibold text-sm leading-tight">{patient.name}</p>
            <p className="text-xs text-gray-500">{patient.ward} · {patient.bed}</p>
          </div>
        </div>
        <div className="flex flex-col items-end gap-1">
          <span className={`text-xs px-2 py-0.5 rounded-full font-semibold ${priorityColors[patient.priority]}`}>{patient.priority}</span>
          {patient.flagged && <span className="text-xs bg-red-500 text-white px-2 py-0.5 rounded-full flex items-center gap-1"><Zap className="w-2.5 h-2.5" /> Flagged</span>}
        </div>
      </div>
      <p className="text-xs text-gray-500 mt-1.5">{patient.disease}</p>
      <div className="flex items-center gap-2 mt-2">
        <RiskRing score={patient.riskScore} size={32} />
        <div className="flex gap-1.5 flex-wrap">
          <span className={`text-xs px-1.5 py-0.5 rounded ${patient.vitals.heartRate > 110 ? "bg-red-100 text-red-600 font-bold" : "bg-gray-100 text-gray-600"}`}>♥ {patient.vitals.heartRate}</span>
          <span className={`text-xs px-1.5 py-0.5 rounded ${patient.vitals.oxygen < 92 ? "bg-red-100 text-red-600 font-bold" : "bg-gray-100 text-gray-600"}`}>O₂ {patient.vitals.oxygen}%</span>
        </div>
      </div>
      <div className="flex gap-2 mt-2">
        {pendingCount > 0 && <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full">{pendingCount} pending</span>}
        {overdueCount > 0 && <span className="text-xs bg-red-100 text-red-700 px-2 py-0.5 rounded-full font-bold">{overdueCount} overdue!</span>}
      </div>
    </motion.div>
  );
}

// Escalation Badge
function EscalationBadge({ level }: { level: EscalationLevel }) {
  const configs = {
    1: { label: "L1 Routine", color: "bg-gray-100 text-gray-600", dot: "bg-gray-400" },
    2: { label: "L2 Watch", color: "bg-blue-100 text-blue-600", dot: "bg-blue-500" },
    3: { label: "L3 Concern", color: "bg-amber-100 text-amber-700", dot: "bg-amber-500" },
    4: { label: "L4 Urgent", color: "bg-orange-100 text-orange-700", dot: "bg-orange-500" },
    5: { label: "L5 Critical", color: "bg-red-100 text-red-700 font-bold", dot: "bg-red-500 animate-pulse" },
  }[level];
  return (
    <span className={`inline-flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-full ${configs.color}`}>
      <span className={`w-1.5 h-1.5 rounded-full ${configs.dot}`} />
      {configs.label}
    </span>
  );
}

// ─── Sidebar Component ────────────────────────────────────────────────────────
function Sidebar({ active, onChange, alertCount, collapsed, onToggle }: {
  active: SidebarView; onChange: (v: SidebarView) => void; alertCount: number; collapsed: boolean; onToggle: () => void;
}) {
  const items: { id: SidebarView; icon: React.ReactNode; label: string; badge?: number }[] = [
    { id: "overview", icon: <LayoutDashboard className="w-4 h-4" />, label: "Overview" },
    { id: "patients", icon: <Users className="w-4 h-4" />, label: "Patient Care" },
    { id: "escalation", icon: <Siren className="w-4 h-4" />, label: "Escalation" },
    { id: "alerts", icon: <Bell className="w-4 h-4" />, label: "Live Alerts", badge: alertCount },
    { id: "handover", icon: <CalendarClock className="w-4 h-4" />, label: "Shift Handover" },
    { id: "history", icon: <History className="w-4 h-4" />, label: "Patient History" },
    { id: "analytics", icon: <BarChart3 className="w-4 h-4" />, label: "Analytics" },
  ];

  return (
    <motion.aside
      animate={{ width: collapsed ? 64 : 220 }}
      transition={{ duration: 0.3, ease: "easeInOut" }}
      className="h-full flex-shrink-0 glass border-r border-white/30 flex flex-col py-4 overflow-hidden"
    >
      <div className="flex items-center justify-between px-3 mb-6">
        {!collapsed && (
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-xl flex items-center justify-center">
              <Stethoscope className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-sm text-gray-800">WardWatch</span>
          </div>
        )}
        <button onClick={onToggle} className="w-7 h-7 rounded-lg hover:bg-white/50 flex items-center justify-center transition-colors ml-auto">
          {collapsed ? <ChevronRight className="w-4 h-4 text-gray-500" /> : <ChevronLeft className="w-4 h-4 text-gray-500" />}
        </button>
      </div>

      <nav className="flex-1 space-y-1 px-2">
        {items.map(item => (
          <button key={item.id} onClick={() => onChange(item.id)}
            className={`w-full flex items-center gap-3 px-2.5 py-2.5 rounded-xl text-sm font-medium transition-all relative ${active === item.id ? "bg-blue-500 text-white shadow-sm" : "text-gray-600 hover:bg-white/50"}`}>
            <span className="flex-shrink-0">{item.icon}</span>
            {!collapsed && <span className="whitespace-nowrap">{item.label}</span>}
            {item.badge != null && item.badge > 0 && (
              <span className={`ml-auto text-xs font-bold px-1.5 py-0.5 rounded-full ${active === item.id ? "bg-white text-blue-600" : "bg-red-500 text-white"}`}>
                {item.badge}
              </span>
            )}
          </button>
        ))}
      </nav>

      <div className="px-2 mt-4 space-y-1 border-t border-white/20 pt-3">
        {!collapsed && (
          <div className="px-2.5 py-2 text-xs text-gray-400">
            <p className="font-medium text-gray-600">Nurse Deepa</p>
            <p>Morning Shift · ICU</p>
          </div>
        )}
        <button className="w-full flex items-center gap-3 px-2.5 py-2 rounded-xl text-sm text-gray-500 hover:bg-white/40 transition-colors">
          <Settings className="w-4 h-4 flex-shrink-0" />
          {!collapsed && "Settings"}
        </button>
      </div>
    </motion.aside>
  );
}

// ─── Header Component ─────────────────────────────────────────────────────────
function DashboardHeader({ patients, alerts, view }: { patients: NursePatient[]; alerts: RealTimeAlert[]; view: SidebarView }) {
  const unacked = alerts.filter(a => !a.acknowledged).length;
  const critical = patients.filter(p => p.severity === "critical").length;
  const flagged = patients.filter(p => p.flagged).length;
  const now = new Date();
  const timeStr = now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  const dateStr = now.toLocaleDateString("en-IN", { weekday: "short", day: "numeric", month: "short" });
  const viewLabels: Record<SidebarView, string> = {
    overview: "Shift Overview", patients: "Patient Care", handover: "Shift Handover",
    escalation: "Escalation Centre", alerts: "Live Alerts & Risk", history: "Patient History", analytics: "Analytics",
  };

  return (
    <header className="glass border-b border-white/30 px-6 py-4 flex items-center justify-between flex-shrink-0">
      <div>
        <h1 className="text-xl font-bold text-gray-900">{viewLabels[view]}</h1>
      </div>
      <div className="flex items-center gap-4">
        {critical > 0 && (
          <div className="flex items-center gap-1.5 bg-red-50 border border-red-200 px-3 py-1.5 rounded-xl">
            <ShieldAlert className="w-3.5 h-3.5 text-red-600" />
            <span className="text-xs font-bold text-red-600">{critical} Critical</span>
          </div>
        )}
        {flagged > 0 && (
          <div className="flex items-center gap-1.5 bg-orange-50 border border-orange-200 px-3 py-1.5 rounded-xl">
            <AlertTriangle className="w-3.5 h-3.5 text-orange-600" />
            <span className="text-xs font-bold text-orange-600">{flagged} Flagged</span>
          </div>
        )}
        <div className="relative">
          <div className="flex items-center gap-1.5 bg-white/50 border border-white/40 px-3 py-1.5 rounded-xl">
            <Bell className="w-3.5 h-3.5 text-gray-600" />
            <span className="text-xs font-semibold text-gray-700">{unacked} Alerts</span>
          </div>
          {unacked > 0 && <span className="absolute -top-1 -right-1 w-4 h-4 bg-red-500 rounded-full flex items-center justify-center text-white text-xs font-bold animate-pulse">{unacked}</span>}
        </div>
        <div className="text-right">
          <p className="text-lg font-bold text-gray-800 font-mono">{timeStr}</p>
          <p className="text-xs text-gray-400">Morning Shift</p>
        </div>
      </div>
    </header>
  );
}

// ─── View: Overview ───────────────────────────────────────────────────────────
function OverviewView({ patients, alerts }: { patients: NursePatient[]; alerts: RealTimeAlert[] }) {
  const totalPatients = patients.length;
  const criticalCount = patients.filter(p => p.severity === "critical").length;
  const pendingTasks = patients.flatMap(p => p.tasks).filter(t => t.status === "pending").length;
  const completedTasks = patients.flatMap(p => p.tasks).filter(t => t.status === "completed").length;
  const overdueTasks = patients.flatMap(p => p.tasks).filter(t => t.status === "pending" && Date.now() - t.assignedAt - t.dueDuration > 0).length;
  const flagged = patients.filter(p => p.flagged).length;
  const unacked = alerts.filter(a => !a.acknowledged).length;
  const avgRisk = Math.round(patients.reduce((s, p) => s + p.riskScore, 0) / patients.length);

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible" className="space-y-5">
      <div className="grid grid-cols-4 gap-4">
        {[
          { label: "Total Patients", value: totalPatients, icon: <User className="w-5 h-5 text-blue-600" />, bg: "bg-blue-100", color: "" },
          { label: "Critical", value: criticalCount, icon: <ShieldAlert className="w-5 h-5 text-red-600" />, bg: "bg-red-100", color: "text-red-600" },
          { label: "Flagged", value: flagged, icon: <Zap className="w-5 h-5 text-orange-500" />, bg: "bg-orange-100", color: flagged > 0 ? "text-orange-600" : "" },
          { label: "Avg Risk Score", value: avgRisk, icon: <Brain className="w-5 h-5 text-purple-600" />, bg: "bg-purple-100", color: avgRisk >= 50 ? "text-red-500" : "text-green-600" },
        ].map(s => (
          <motion.div key={s.label} variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
            <div className="flex items-center gap-3">
              <div className={`w-10 h-10 ${s.bg} rounded-2xl flex items-center justify-center`}>{s.icon}</div>
              <div>
                <p className="text-xs text-gray-500">{s.label}</p>
                <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
      <div className="grid grid-cols-4 gap-4">
        {[
          { label: "Pending Tasks", value: pendingTasks, icon: <ClipboardList className="w-5 h-5 text-blue-500" />, bg: "bg-blue-100", color: "" },
          { label: "Completed", value: completedTasks, icon: <CheckCircle2 className="w-5 h-5 text-green-600" />, bg: "bg-green-100", color: "text-green-600" },
          { label: "Overdue Tasks", value: overdueTasks, icon: <Clock className="w-5 h-5 text-red-500" />, bg: overdueTasks > 0 ? "bg-red-200" : "bg-gray-100", color: overdueTasks > 0 ? "text-red-600" : "" },
          { label: "Live Alerts", value: unacked, icon: <Bell className="w-5 h-5 text-amber-600" />, bg: "bg-amber-100", color: unacked > 0 ? "text-amber-600" : "" },
        ].map(s => (
          <motion.div key={s.label} variants={itemVariants} className={`glass p-5 rounded-3xl border ${s.label === "Overdue Tasks" && overdueTasks > 0 ? "border-red-300 bg-red-50/40" : "border-white/40"}`}>
            <div className="flex items-center gap-3">
              <div className={`w-10 h-10 ${s.bg} rounded-2xl flex items-center justify-center`}>{s.icon}</div>
              <div>
                <p className="text-xs text-gray-500">{s.label}</p>
                <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Patient risk overview */}
      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
        <h3 className="font-bold mb-4 flex items-center gap-2"><Brain className="w-4 h-4 text-purple-500" /> Patient Risk Overview</h3>
        <div className="grid grid-cols-4 gap-3">
          {patients.map(p => (
            <div key={p.id} className={`flex items-center gap-2 p-2.5 rounded-xl border ${p.riskScore >= 70 ? "border-red-200 bg-red-50/40" : p.riskScore >= 40 ? "border-amber-200 bg-amber-50/30" : "border-white/30 bg-white/20"}`}>
              <RiskRing score={p.riskScore} size={40} />
              <div className="min-w-0">
                <p className="text-xs font-semibold truncate">{p.name.split(" ")[0]}</p>
                <p className="text-xs text-gray-500">{p.bed}</p>
                <EscalationBadge level={p.escalationLevel} />
              </div>
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}

// ─── View: Patient Care ───────────────────────────────────────────────────────
function PatientCareView({
  patients, selectedId, setSelectedId, filter, setFilter,
  handleCompleteTask, handleMarkVitalsChecked, handleCallDoctor, handleRegenTasks,
}: {
  patients: NursePatient[]; selectedId: string; setSelectedId: (id: string) => void;
  filter: "all" | Severity; setFilter: (f: "all" | Severity) => void;
  handleCompleteTask: (pid: string, tid: string) => void;
  handleMarkVitalsChecked: (pid: string) => void;
  handleCallDoctor: (p: NursePatient) => void;
  handleRegenTasks: (pid: string) => void;
}) {
  const selectedPatient = patients.find(p => p.id === selectedId) ?? patients[0];
  const filteredPatients = filter === "all" ? patients : patients.filter(p => p.severity === filter);

  return (
    <div className="grid grid-cols-3 gap-5 h-full">
      {/* LEFT: Patient List */}
      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40 flex flex-col gap-4">
        <div>
          <h3 className="font-bold mb-3">Patient Care List</h3>
          <div className="flex gap-1 bg-white/30 p-1 rounded-xl">
            {(["all", "critical", "moderate", "stable"] as const).map(f => (
              <button key={f} onClick={() => setFilter(f)}
                className={`flex-1 text-xs py-1.5 rounded-lg font-medium transition-all capitalize ${filter === f ? (f === "critical" ? "bg-red-500 text-white" : f === "moderate" ? "bg-amber-500 text-white" : f === "stable" ? "bg-green-500 text-white" : "bg-blue-500 text-white") + " shadow" : "text-gray-500 hover:bg-white/50"}`}>
                {f}
              </button>
            ))}
          </div>
        </div>
        <div className="space-y-2.5 overflow-y-auto flex-1 pr-1">
          <AnimatePresence>
            {filteredPatients.map(p => <PatientCard key={p.id} patient={p} selected={selectedId === p.id} onSelect={() => setSelectedId(p.id)} />)}
          </AnimatePresence>
        </div>
      </motion.div>

      {/* CENTER: Task Panel */}
      {selectedPatient && (
        <motion.div key={selectedPatient.id} variants={itemVariants} initial="hidden" animate="visible" className="glass p-5 rounded-3xl border border-white/40 flex flex-col gap-4">
          <div className="flex items-start justify-between">
            <div>
              <h3 className="text-xl font-bold">{selectedPatient.name}</h3>
              <p className="text-sm text-gray-500">{selectedPatient.ward} · Bed {selectedPatient.bed} · Age {selectedPatient.age}</p>
              <p className="text-xs text-gray-400">{selectedPatient.disease}</p>
            </div>
            <div className="flex flex-col items-end gap-1">
              <EscalationBadge level={selectedPatient.escalationLevel} />
              <span className="text-xs text-gray-500">Assigned: {selectedPatient.assignedNurse}</span>
            </div>
          </div>

          {/* Quick Actions */}
          <div>
            <p className="text-xs text-gray-500 mb-2">Quick Actions</p>
            <div className="flex gap-2 flex-wrap">
              <button onClick={() => handleMarkVitalsChecked(selectedPatient.id)} className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-500 text-white rounded-xl text-xs font-medium hover:bg-blue-600 transition-colors">
                <Activity className="w-3.5 h-3.5" /> Check Vitals
              </button>
              <button onClick={() => handleCallDoctor(selectedPatient)} className="flex items-center gap-1.5 px-3 py-1.5 bg-red-500 text-white rounded-xl text-xs font-medium hover:bg-red-600 transition-colors">
                <Phone className="w-3.5 h-3.5" /> Call Doctor
              </button>
              <button onClick={() => { const t = selectedPatient.tasks.find(t => t.status === "pending"); if (t) handleCompleteTask(selectedPatient.id, t.id); }} className="flex items-center gap-1.5 px-3 py-1.5 bg-green-500 text-white rounded-xl text-xs font-medium hover:bg-green-600 transition-colors">
                <CheckCircle2 className="w-3.5 h-3.5" /> Complete Next
              </button>
              <button onClick={() => handleRegenTasks(selectedPatient.id)} className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-500 text-white rounded-xl text-xs font-medium hover:bg-purple-600 transition-colors">
                <RefreshCw className="w-3.5 h-3.5" /> Auto-Regen
              </button>
            </div>
          </div>

          {/* Risk + Allergies */}
          <div className="flex gap-3">
            <div className="flex items-center gap-2 bg-white/30 rounded-xl p-2 border border-white/40 flex-1">
              <RiskRing score={selectedPatient.riskScore} size={48} />
              <div>
                <p className="text-xs font-semibold text-gray-700">Risk Score</p>
                {selectedPatient.riskFactors.slice(0, 3).map(rf => (
                  <p key={rf} className="text-xs text-red-500">• {rf}</p>
                ))}
              </div>
            </div>
            {selectedPatient.allergies.length > 0 && (
              <div className="bg-amber-50 border border-amber-200 rounded-xl p-2 flex-1">
                <p className="text-xs font-bold text-amber-700 mb-1">⚠ Allergies</p>
                {selectedPatient.allergies.map(a => <p key={a} className="text-xs text-amber-600">• {a}</p>)}
              </div>
            )}
          </div>

          {/* Task Checklist */}
          <div className="flex-1">
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs text-gray-500 font-semibold flex items-center gap-1"><Brain className="w-3.5 h-3.5 text-purple-500" /> AI Task Intelligence</p>
              <span className="text-xs text-gray-400">{selectedPatient.tasks.filter(t => t.status === "completed").length}/{selectedPatient.tasks.length} done</span>
            </div>
            <div className="w-full bg-gray-100 h-1.5 rounded-full mb-3">
              <div className="h-1.5 rounded-full bg-green-500 transition-all duration-500" style={{ width: `${(selectedPatient.tasks.filter(t => t.status === "completed").length / Math.max(selectedPatient.tasks.length, 1)) * 100}%` }} />
            </div>
            <div className="space-y-1.5 overflow-y-auto max-h-52">
              <AnimatePresence>
                {selectedPatient.tasks.map(task => <TaskRow key={task.id} task={task} onComplete={(id) => handleCompleteTask(selectedPatient.id, id)} />)}
              </AnimatePresence>
            </div>
          </div>

          <div className="flex items-center gap-1.5 text-xs text-gray-400 pt-2 border-t border-white/30">
            <Clock className="w-3.5 h-3.5" /> Vitals last checked: {formatElapsed(selectedPatient.vitals.lastChecked)}
          </div>
        </motion.div>
      )}

      {/* RIGHT: Live Vitals + ECG */}
      {selectedPatient && (
        <motion.div key={`vitals-${selectedPatient.id}`} variants={itemVariants} initial="hidden" animate="visible" className="glass p-5 rounded-3xl border border-white/40 flex flex-col gap-4">
          <div>
            <h3 className="text-xl font-bold">Live Vitals</h3>
            <p className="text-sm text-gray-500">{selectedPatient.name}</p>
          </div>

          {/* ECG Monitor */}
          <ECGMonitor patient={selectedPatient} />

          {/* Vitals Grid */}
          <div className="grid grid-cols-2 gap-2.5">
            <VitalBadge icon={<Heart className="w-4 h-4" />} label="Heart Rate" value={`${selectedPatient.vitals.heartRate} bpm`} abnormal={selectedPatient.vitals.heartRate > 110 || selectedPatient.vitals.heartRate < 50} trend={selectedPatient.vitals.heartRate > 100 ? "up" : "stable"} />
            <VitalBadge icon={<Wind className="w-4 h-4" />} label="SpO₂" value={`${selectedPatient.vitals.oxygen}%`} abnormal={selectedPatient.vitals.oxygen < 92} trend={selectedPatient.vitals.oxygen < 94 ? "down" : "stable"} />
            <VitalBadge icon={<Activity className="w-4 h-4" />} label="Blood Pressure" value={`${selectedPatient.vitals.bpSystolic}/${selectedPatient.vitals.bpDiastolic}`} abnormal={selectedPatient.vitals.bpSystolic > 160 || selectedPatient.vitals.bpDiastolic > 100} trend={selectedPatient.vitals.bpSystolic > 140 ? "up" : "stable"} />
            <VitalBadge icon={<Thermometer className="w-4 h-4" />} label="Temp" value={`${selectedPatient.vitals.temperature}°C`} abnormal={selectedPatient.vitals.temperature > 38.5} trend={selectedPatient.vitals.temperature > 38 ? "up" : "stable"} />
            <VitalBadge icon={<Wind className="w-4 h-4" />} label="Resp. Rate" value={`${selectedPatient.vitals.respiratoryRate}/min`} abnormal={selectedPatient.vitals.respiratoryRate > 22} trend={selectedPatient.vitals.respiratoryRate > 20 ? "up" : "stable"} />
          </div>

          {/* Abnormal callout */}
          {isVitalAbnormal(selectedPatient.vitals) && (
            <div className="bg-red-50 border border-red-300 rounded-2xl p-3 flex items-start gap-2">
              <AlertTriangle className="w-4 h-4 text-red-500 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-red-700 text-xs font-bold">Abnormal Vitals Detected</p>
                <ul className="mt-1 space-y-0.5">
                  {selectedPatient.vitals.oxygen < 92 && <li className="text-xs text-red-600">• SpO₂ {selectedPatient.vitals.oxygen}% — below 92%</li>}
                  {selectedPatient.vitals.heartRate > 110 && <li className="text-xs text-red-600">• HR {selectedPatient.vitals.heartRate} bpm — tachycardia</li>}
                  {selectedPatient.vitals.heartRate < 50 && <li className="text-xs text-red-600">• HR {selectedPatient.vitals.heartRate} bpm — bradycardia</li>}
                  {selectedPatient.vitals.temperature > 38.5 && <li className="text-xs text-red-600">• Temp {selectedPatient.vitals.temperature}°C — fever</li>}
                  {selectedPatient.vitals.respiratoryRate > 22 && <li className="text-xs text-red-600">• RR {selectedPatient.vitals.respiratoryRate}/min — tachypnea</li>}
                </ul>
              </div>
            </div>
          )}

          {/* All Patients Quick Status */}
          <div>
            <p className="text-xs text-gray-500 font-semibold mb-2">All Patients — Quick Status</p>
            <div className="space-y-1.5 overflow-y-auto max-h-44">
              {patients.map(p => (
                <div key={p.id} onClick={() => setSelectedId(p.id)}
                  className={`flex items-center justify-between p-2 rounded-xl cursor-pointer transition-all border ${p.id === selectedId ? "border-blue-300 bg-blue-50/50" : p.flagged ? "border-red-200 bg-red-50/30" : "border-white/30 hover:bg-white/30"}`}>
                  <div className="flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-full ${p.severity === "critical" ? "bg-red-500" : p.severity === "moderate" ? "bg-amber-500" : "bg-green-500"}`} />
                    <span className="text-xs font-medium truncate max-w-[80px]">{p.name.split(" ")[0]}</span>
                  </div>
                  <div className="flex gap-1">
                    <span className={`text-xs px-1.5 py-0.5 rounded ${p.vitals.heartRate > 110 ? "bg-red-100 text-red-600" : "bg-gray-100 text-gray-500"}`}>♥{p.vitals.heartRate}</span>
                    <span className={`text-xs px-1.5 py-0.5 rounded ${p.vitals.oxygen < 92 ? "bg-red-100 text-red-600" : "bg-gray-100 text-gray-500"}`}>O₂{p.vitals.oxygen}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}

// ─── View: Shift Handover ─────────────────────────────────────────────────────
function HandoverView({ handovers, patients }: { handovers: ShiftHandover[]; patients: NursePatient[] }) {
  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible" className="space-y-5">
      <div className="grid grid-cols-2 gap-5">
        {handovers.map(h => (
          <motion.div key={h.id} variants={itemVariants} className={`glass p-5 rounded-3xl border ${h.status === "in-progress" ? "border-blue-300 bg-blue-50/20" : "border-white/40"}`}>
            <div className="flex items-start justify-between mb-3">
              <div>
                <h3 className="font-bold">{h.fromNurse} → {h.toNurse}</h3>
                <p className="text-xs text-gray-500">Shift end: {h.shiftEnd}</p>
              </div>
              <span className={`text-xs px-2.5 py-1 rounded-full font-semibold ${h.status === "in-progress" ? "bg-blue-100 text-blue-700" : h.status === "completed" ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-600"}`}>
                {h.status}
              </span>
            </div>
            <p className="text-sm text-gray-700 mb-3 leading-relaxed">{h.summary}</p>
            <div className="space-y-2">
              <p className="text-xs font-bold text-red-700 flex items-center gap-1"><AlertTriangle className="w-3.5 h-3.5" /> Critical Notes</p>
              {h.criticalNotes.map((n, i) => (
                <div key={i} className="flex items-start gap-2 bg-red-50 rounded-xl p-2 text-xs text-red-700">
                  <span className="text-red-400 flex-shrink-0">•</span>{n}
                </div>
              ))}
            </div>
            <div className="space-y-2 mt-3">
              <p className="text-xs font-bold text-amber-700 flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> Pending Tasks to Hand Over</p>
              {h.pendingTasks.map((t, i) => (
                <div key={i} className="flex items-start gap-2 bg-amber-50 rounded-xl p-2 text-xs text-amber-700">
                  <span className="text-amber-400 flex-shrink-0">→</span>{t}
                </div>
              ))}
            </div>
          </motion.div>
        ))}
      </div>

      {/* Patient assignment summary */}
      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
        <h3 className="font-bold mb-4 flex items-center gap-2"><UserCheck className="w-4 h-4 text-blue-500" /> Nurse Assignments</h3>
        <div className="grid grid-cols-4 gap-3">
          {NURSES.map(nurse => {
            const assigned = patients.filter(p => p.assignedNurse === nurse);
            return (
              <div key={nurse} className="bg-white/30 rounded-2xl border border-white/40 p-3">
                <p className="text-xs font-semibold text-gray-700">{nurse}</p>
                <p className="text-xs text-gray-500 mb-2">{assigned.length} patients</p>
                {assigned.map(p => (
                  <div key={p.id} className="flex items-center gap-1.5 mb-1">
                    <div className={`w-1.5 h-1.5 rounded-full ${p.severity === "critical" ? "bg-red-500" : p.severity === "moderate" ? "bg-amber-500" : "bg-green-500"}`} />
                    <span className="text-xs truncate">{p.name.split(" ")[0]}</span>
                  </div>
                ))}
              </div>
            );
          })}
        </div>
      </motion.div>
    </motion.div>
  );
}

// ─── View: Escalation ─────────────────────────────────────────────────────────
function EscalationView({ patients, escalations, onAcknowledge }: { patients: NursePatient[]; escalations: EscalationRecord[]; onAcknowledge: (id: string) => void }) {
  const levelLabels = ["", "Routine", "Watch", "Concern", "Urgent", "Code Critical"];
  const levelColors = ["", "text-gray-500", "text-blue-600", "text-amber-600", "text-orange-600", "text-red-600"];
  const levelBgs = ["", "bg-gray-50 border-gray-200", "bg-blue-50 border-blue-200", "bg-amber-50 border-amber-200", "bg-orange-50 border-orange-200", "bg-red-50 border-red-300"];

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible" className="space-y-5">
      {/* Escalation legend */}
      <motion.div variants={itemVariants} className="glass p-4 rounded-3xl border border-white/40">
        <h3 className="font-bold mb-3 flex items-center gap-2"><Layers className="w-4 h-4 text-indigo-500" /> Escalation Protocol</h3>
        <div className="flex gap-3 flex-wrap">
          {[1, 2, 3, 4, 5].map(l => (
            <div key={l} className={`flex items-center gap-2 px-3 py-1.5 rounded-xl border text-xs ${levelBgs[l]}`}>
              <Flame className={`w-3.5 h-3.5 ${levelColors[l]}`} />
              <span className={`font-semibold ${levelColors[l]}`}>L{l} — {levelLabels[l]}</span>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Active escalations */}
      <div className="grid grid-cols-2 gap-4">
        {escalations.map(e => (
          <motion.div key={e.id} variants={itemVariants} className={`glass p-4 rounded-3xl border ${levelBgs[e.level]}`}>
            <div className="flex items-start justify-between mb-2">
              <div>
                <p className="font-bold text-sm">{e.patientName}</p>
                <EscalationBadge level={e.level} />
              </div>
              <span className={`text-xs px-2 py-1 rounded-full font-semibold ${e.status === "open" ? "bg-red-100 text-red-700 animate-pulse" : e.status === "acknowledged" ? "bg-amber-100 text-amber-700" : "bg-green-100 text-green-700"}`}>
                {e.status}
              </span>
            </div>
            <p className="text-xs text-gray-600 mb-2">Reason: {e.reason}</p>
            <p className="text-xs text-gray-500 mb-2">Initiated: {formatElapsed(e.initiatedAt)}</p>
            {e.assignedTo && <p className="text-xs text-blue-600">Assigned to: {e.assignedTo}</p>}
            {e.status !== "resolved" && (
              <button onClick={() => onAcknowledge(e.id)} className="mt-2 text-xs bg-white border border-gray-200 px-3 py-1 rounded-lg hover:bg-gray-50 transition-colors">
                {e.status === "open" ? "Acknowledge" : "Mark Resolved"}
              </button>
            )}
          </motion.div>
        ))}
        {escalations.length === 0 && (
          <motion.div variants={itemVariants} className="col-span-2 glass p-8 rounded-3xl border border-white/40 text-center">
            <CheckCircle2 className="w-8 h-8 text-green-500 mx-auto mb-2" />
            <p className="text-gray-500 font-medium">No active escalations</p>
            <p className="text-xs text-gray-400">All patients within normal escalation parameters</p>
          </motion.div>
        )}
      </div>

      {/* All patients escalation status */}
      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
        <h3 className="font-bold mb-3">All Patients — Escalation Status</h3>
        <div className="grid grid-cols-4 gap-3">
          {patients.map(p => (
            <div key={p.id} className={`p-3 rounded-2xl border ${levelBgs[p.escalationLevel]}`}>
              <p className="text-xs font-semibold">{p.name.split(" ")[0]}</p>
              <p className="text-xs text-gray-500 mb-1">{p.bed} · {p.ward}</p>
              <EscalationBadge level={p.escalationLevel} />
              <p className="text-xs text-gray-500 mt-1">Risk: {p.riskScore}/100</p>
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}

// ─── View: Alerts ─────────────────────────────────────────────────────────────
function AlertsView({ alerts, patients, onAcknowledge }: { alerts: RealTimeAlert[]; patients: NursePatient[]; onAcknowledge: (id: string) => void }) {
  const typeIcons: Record<string, React.ReactNode> = {
    vitals: <Activity className="w-4 h-4" />,
    risk: <Brain className="w-4 h-4" />,
    escalation: <Siren className="w-4 h-4" />,
    task: <ClipboardList className="w-4 h-4" />,
    system: <AlertCircle className="w-4 h-4" />,
  };

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible" className="space-y-5">
      {/* Risk prediction panel */}
      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
        <h3 className="font-bold mb-4 flex items-center gap-2"><Brain className="w-4 h-4 text-purple-500" /> AI Risk Prediction</h3>
        <div className="grid grid-cols-4 gap-3">
          {patients.filter(p => p.riskScore >= 30).sort((a, b) => b.riskScore - a.riskScore).map(p => (
            <div key={p.id} className={`p-3 rounded-2xl border ${p.riskScore >= 70 ? "bg-red-50 border-red-200" : p.riskScore >= 50 ? "bg-amber-50 border-amber-200" : "bg-white/30 border-white/40"}`}>
              <div className="flex items-center gap-2 mb-2">
                <RiskRing score={p.riskScore} size={36} />
                <div>
                  <p className="text-xs font-bold">{p.name.split(" ")[0]}</p>
                  <p className="text-xs text-gray-500">{p.disease}</p>
                </div>
              </div>
              <div className="space-y-0.5">
                {p.riskFactors.slice(0, 2).map(rf => (
                  <p key={rf} className="text-xs text-red-500">⚠ {rf}</p>
                ))}
              </div>
              {p.riskScore >= 70 && <p className="text-xs text-red-600 font-semibold mt-1 animate-pulse">Deterioration risk HIGH</p>}
            </div>
          ))}
        </div>
      </motion.div>

      {/* Live alerts feed */}
      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-bold flex items-center gap-2"><Bell className="w-4 h-4 text-amber-500" /> Live Alert Feed</h3>
          <span className="text-xs text-gray-400">{alerts.filter(a => !a.acknowledged).length} unacknowledged</span>
        </div>
        <div className="space-y-2.5 max-h-96 overflow-y-auto">
          <AnimatePresence>
            {alerts.map(a => (
              <motion.div key={a.id} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}
                className={`flex items-start gap-3 p-3 rounded-2xl border transition-all ${a.acknowledged ? "opacity-50 bg-white/20 border-white/20" : a.severity === "critical" ? "bg-red-50 border-red-200" : a.severity === "moderate" ? "bg-amber-50 border-amber-200" : "bg-white/30 border-white/30"}`}>
                <span className={a.severity === "critical" ? "text-red-500" : a.severity === "moderate" ? "text-amber-500" : "text-gray-400"}>
                  {typeIcons[a.type]}
                </span>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    {a.patientName && <span className="text-xs font-bold">{a.patientName}</span>}
                    <span className={`text-xs px-1.5 py-0.5 rounded-full font-medium ${a.severity === "critical" ? "bg-red-100 text-red-700" : a.severity === "moderate" ? "bg-amber-100 text-amber-700" : "bg-gray-100 text-gray-600"}`}>{a.type}</span>
                  </div>
                  <p className="text-xs text-gray-700 mt-0.5">{a.message}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{formatElapsed(a.timestamp)}</p>
                </div>
                {!a.acknowledged && (
                  <button onClick={() => onAcknowledge(a.id)} className="text-xs bg-white border border-gray-200 px-2 py-1 rounded-lg hover:bg-gray-50 transition-colors flex-shrink-0">
                    Ack
                  </button>
                )}
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      </motion.div>
    </motion.div>
  );
}

// ─── View: Patient History ────────────────────────────────────────────────────
function HistoryView({ patients, selectedId, setSelectedId }: { patients: NursePatient[]; selectedId: string; setSelectedId: (id: string) => void }) {
  const patient = patients.find(p => p.id === selectedId) ?? patients[0];
  const typeIcons: Record<string, React.ReactNode> = {
    admission: <User className="w-3.5 h-3.5 text-purple-500" />,
    vitals: <Activity className="w-3.5 h-3.5 text-blue-500" />,
    task: <CheckCircle2 className="w-3.5 h-3.5 text-green-500" />,
    medication: <Zap className="w-3.5 h-3.5 text-amber-500" />,
    doctor: <Stethoscope className="w-3.5 h-3.5 text-indigo-500" />,
    alert: <AlertTriangle className="w-3.5 h-3.5 text-red-500" />,
  };

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible" className="grid grid-cols-3 gap-5">
      {/* Patient selector */}
      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
        <h3 className="font-bold mb-3 flex items-center gap-2"><BookOpen className="w-4 h-4 text-indigo-500" /> Patient Records</h3>
        <div className="space-y-2 overflow-y-auto max-h-[600px]">
          {patients.map(p => (
            <button key={p.id} onClick={() => setSelectedId(p.id)}
              className={`w-full text-left p-3 rounded-2xl border transition-all ${p.id === selectedId ? "border-blue-300 bg-blue-50/50" : "border-white/30 hover:bg-white/30"}`}>
              <div className="flex items-center gap-2">
                <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold ${p.severity === "critical" ? "bg-red-100 text-red-600" : p.severity === "moderate" ? "bg-amber-100 text-amber-600" : "bg-green-100 text-green-600"}`}>{p.name[0]}</div>
                <div>
                  <p className="text-xs font-semibold">{p.name}</p>
                  <p className="text-xs text-gray-500">{p.disease}</p>
                </div>
              </div>
            </button>
          ))}
        </div>
      </motion.div>

      {/* History snapshot */}
      {patient && (
        <motion.div key={`hist-${patient.id}`} variants={itemVariants} initial="hidden" animate="visible" className="glass p-5 rounded-3xl border border-white/40 col-span-2">
          <div className="flex items-start justify-between mb-4">
            <div>
              <h3 className="text-xl font-bold">{patient.name}</h3>
              <p className="text-sm text-gray-500">Age {patient.age} · {patient.ward} · Bed {patient.bed}</p>
              <p className="text-xs text-gray-400">Admitted: {formatDate(patient.admittedAt)}</p>
            </div>
            <EscalationBadge level={patient.escalationLevel} />
          </div>

          {/* Medications */}
          <div className="flex gap-3 mb-4">
            <div className="flex-1 bg-white/30 rounded-2xl border border-white/40 p-3">
              <p className="text-xs font-bold text-gray-700 mb-2">Current Medications</p>
              {patient.medications.map(m => <p key={m} className="text-xs text-gray-600">• {m}</p>)}
            </div>
            {patient.allergies.length > 0 && (
              <div className="flex-1 bg-amber-50 border border-amber-200 rounded-2xl p-3">
                <p className="text-xs font-bold text-amber-700 mb-2">⚠ Allergies</p>
                {patient.allergies.map(a => <p key={a} className="text-xs text-amber-600">• {a}</p>)}
              </div>
            )}
            <div className="flex-1 bg-white/30 rounded-2xl border border-white/40 p-3">
              <p className="text-xs font-bold text-gray-700 mb-2">Clinical Notes</p>
              <p className="text-xs text-gray-600 leading-relaxed">{patient.notes}</p>
            </div>
          </div>

          {/* Timeline */}
          <p className="text-xs font-bold text-gray-700 mb-3">Clinical Timeline</p>
          <div className="space-y-3 overflow-y-auto max-h-72">
            {patient.history.map((event, i) => (
              <div key={i} className="flex gap-3 items-start">
                <div className="flex flex-col items-center">
                  <div className="w-7 h-7 rounded-full bg-white border border-gray-200 flex items-center justify-center flex-shrink-0">{typeIcons[event.type]}</div>
                  {i < patient.history.length - 1 && <div className="w-0.5 h-4 bg-gray-200 mt-1" />}
                </div>
                <div className="flex-1 pb-2">
                  <p className="text-xs font-medium text-gray-700">{event.description}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{formatDate(event.timestamp)}</p>
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      )}
    </motion.div>
  );
}

// ─── View: Analytics ─────────────────────────────────────────────────────────
function AnalyticsView({ patients }: { patients: NursePatient[] }) {
  const critPct = Math.round((patients.filter(p => p.severity === "critical").length / patients.length) * 100);
  const modPct = Math.round((patients.filter(p => p.severity === "moderate").length / patients.length) * 100);
  const stabPct = 100 - critPct - modPct;
  const taskCompletion = Math.round((patients.flatMap(p => p.tasks).filter(t => t.status === "completed").length / Math.max(patients.flatMap(p => p.tasks).length, 1)) * 100);
  const avgRisk = Math.round(patients.reduce((s, p) => s + p.riskScore, 0) / patients.length);

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible" className="space-y-5">
      <div className="grid grid-cols-3 gap-5">
        <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
          <h3 className="font-bold mb-4 flex items-center gap-2"><Users className="w-4 h-4 text-blue-500" /> Severity Distribution</h3>
          <div className="space-y-3">
            {[{ label: "Critical", pct: critPct, color: "bg-red-500" }, { label: "Moderate", pct: modPct, color: "bg-amber-500" }, { label: "Stable", pct: stabPct, color: "bg-green-500" }].map(s => (
              <div key={s.label}>
                <div className="flex justify-between text-xs mb-1"><span className="font-medium">{s.label}</span><span className="text-gray-500">{s.pct}%</span></div>
                <div className="h-2 bg-gray-100 rounded-full overflow-hidden"><div className={`h-full ${s.color} rounded-full transition-all`} style={{ width: `${s.pct}%` }} /></div>
              </div>
            ))}
          </div>
        </motion.div>

        <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
          <h3 className="font-bold mb-4 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-green-500" /> Task Completion</h3>
          <div className="flex items-center justify-center">
            <svg width="120" height="120" viewBox="0 0 120 120">
              <circle cx="60" cy="60" r="48" fill="none" stroke="#e5e7eb" strokeWidth="12" />
              <circle cx="60" cy="60" r="48" fill="none" stroke={taskCompletion >= 70 ? "#22c55e" : taskCompletion >= 40 ? "#f59e0b" : "#ef4444"} strokeWidth="12"
                strokeDasharray={`${(taskCompletion / 100) * 2 * Math.PI * 48} ${2 * Math.PI * 48 * (1 - taskCompletion / 100)}`} strokeLinecap="round" transform="rotate(-90 60 60)" />
              <text x="60" y="60" dominantBaseline="middle" textAnchor="middle" fontSize="22" fontWeight="bold" fill="#1f2937">{taskCompletion}%</text>
              <text x="60" y="78" dominantBaseline="middle" textAnchor="middle" fontSize="10" fill="#6b7280">completed</text>
            </svg>
          </div>
        </motion.div>

        <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
          <h3 className="font-bold mb-4 flex items-center gap-2"><BarChart3 className="w-4 h-4 text-indigo-500" /> Ward Load</h3>
          <div className="space-y-2">
            {Array.from(new Set(patients.map(p => p.ward))).map(ward => {
              const wardPatients = patients.filter(p => p.ward === ward);
              const pct = Math.round((wardPatients.length / patients.length) * 100);
              return (
                <div key={ward}>
                  <div className="flex justify-between text-xs mb-1"><span className="font-medium truncate max-w-24">{ward}</span><span className="text-gray-500">{wardPatients.length} pts</span></div>
                  <div className="h-2 bg-gray-100 rounded-full overflow-hidden"><div className="h-full bg-indigo-400 rounded-full" style={{ width: `${pct}%` }} /></div>
                </div>
              );
            })}
          </div>
        </motion.div>
      </div>

      <motion.div variants={itemVariants} className="glass p-5 rounded-3xl border border-white/40">
        <h3 className="font-bold mb-4">Vital Trends — All Patients</h3>
        <div className="grid grid-cols-4 gap-4">
          {patients.map(p => (
            <div key={p.id} className="bg-white/30 rounded-2xl border border-white/40 p-3">
              <p className="text-xs font-bold mb-2 truncate">{p.name.split(" ")[0]} {p.name.split(" ")[1]?.[0]}.</p>
              <div className="flex items-end gap-0.5 h-10">
                {p.vitalHistory.slice(-6).map((v, i) => (
                  <div key={i} className="flex-1 flex flex-col justify-end">
                    <div className={`rounded-sm ${v.heartRate > 110 ? "bg-red-400" : v.heartRate > 90 ? "bg-amber-400" : "bg-green-400"}`} style={{ height: `${Math.min(100, (v.heartRate / 150) * 100)}%` }} />
                  </div>
                ))}
              </div>
              <p className="text-xs text-gray-400 mt-1">HR trend</p>
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}

// ─── Main Dashboard ────────────────────────────────────────────────────────────
export default function NurseDashboard({ nurseName = "Nurse Lalitha" }: NurseDashboardProps) {
  const [patients, setPatients] = useState<NursePatient[]>([]);
const [loading, setLoading] = useState(true);
const [wardName, setWardName] = useState("");
const [wardOccupiedBeds, setWardOccupiedBeds] = useState(0);
const [wardAvailableBeds, setWardAvailableBeds] = useState(0);

const toNursePatient = (p: any): NursePatient => {
  const severity: Severity =
    p.severity === "critical" || p.severity === "severe"
      ? "critical"
      : p.severity === "moderate"
      ? "moderate"
      : "stable";

  const vitals: Vitals = {
    heartRate: p.vitals?.heartRate ?? 90,
    oxygen: p.vitals?.oxygen ?? 98,
    bpSystolic: p.vitals?.bpSystolic ?? 120,
    bpDiastolic: p.vitals?.bpDiastolic ?? 80,
    temperature: p.vitals?.temperature ?? 37.0,
    respiratoryRate: p.vitals?.respiratoryRate ?? 16,
    lastChecked: Date.now(),
    ecgPoints: generateEcgPoints(p.vitals?.heartRate ?? 90, false),
  };

  const riskScore = computeRiskScore(vitals, severity);

  return {
    id: p.id,
    name: p.name,
    age: p.age ?? 0,
    ward: p.wardName || wardName,
    bed: p.bedNumber || "N/A",
    disease: p.disease || "Unknown",
    severity,
    vitals,
    vitalHistory: generateVitalHistory(severity),
    tasks: generateTasksForSeverity(p.id, severity, isVitalAbnormal(vitals)),
    flagged: isVitalAbnormal(vitals),
    priority: severity === "critical" ? "P1" : severity === "moderate" ? "P2" : "P3",
    riskScore,
    riskFactors: computeRiskFactors(vitals, severity, p.disease || ""),
    escalationLevel: computeEscalationLevel(riskScore, severity),
    assignedNurse: nurseName,
    admittedAt: Date.now() - ((p.daysAdmitted ?? 0) * 24 * 60 * 60 * 1000),
    history: generateHistory(p.id, p.disease || ""),
    allergies: [],
    medications: [],
    notes: p.notes || "",
  };
};

const refreshNurseDashboard = async () => {
  try {
    setLoading(true);
    const data = await api.getNurseDashboard(nurseName);

    setWardName(data.wardName || "");
    setWardOccupiedBeds(data.occupiedBeds || 0);
    setWardAvailableBeds(data.availableBeds || 0);
    setPatients((data.patients || []).map((p: any) => toNursePatient(p)));
  } catch (err) {
    console.error("Failed to load nurse dashboard", err);
  } finally {
    setLoading(false);
  }
};

useEffect(() => {
  refreshNurseDashboard();
  const id = setInterval(refreshNurseDashboard, 3000);
  return () => clearInterval(id);
}, [nurseName]);

  const [selectedId, setSelectedId] = useState<string>(patients[0]?.id ?? "");
  const [filter, setFilter] = useState<"all" | Severity>("all");
  const [view, setView] = useState<SidebarView>("overview");
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [handovers] = useState<ShiftHandover[]>(buildHandovers);
  const [alerts, setAlerts] = useState<RealTimeAlert[]>([]);
  const [escalations, setEscalations] = useState<EscalationRecord[]>([]);
  const [tick, setTick] = useState(0);

  
  // Tick every 30s for vitals fluctuation
  useEffect(() => {
    const interval = setInterval(() => setTick(t => t + 1), 30000);
    return () => clearInterval(interval);
  }, []);

  // Real-time vital fluctuations
  useEffect(() => {
    setPatients(prev => prev.map(p => {
      const delta = (max: number) => (Math.random() - 0.5) * max;
      const newVitals: Vitals = {
        ...p.vitals,
        heartRate: Math.max(40, Math.min(160, Math.round(p.vitals.heartRate + delta(6)))),
        oxygen: Math.max(80, Math.min(100, Math.round(p.vitals.oxygen + delta(3)))),
        bpSystolic: Math.max(90, Math.min(200, Math.round(p.vitals.bpSystolic + delta(8)))),
        bpDiastolic: Math.max(50, Math.min(120, Math.round(p.vitals.bpDiastolic + delta(5)))),
        temperature: Math.max(35, Math.min(41, parseFloat((p.vitals.temperature + delta(0.2)).toFixed(1)))),
        respiratoryRate: Math.max(10, Math.min(35, Math.round(p.vitals.respiratoryRate + delta(3)))),
        ecgPoints: generateEcgPoints(p.vitals.heartRate, isVitalAbnormal(p.vitals)),
      };
      const newRisk = computeRiskScore(newVitals, p.severity);
      const abnormal = isVitalAbnormal(newVitals);
      return {
        ...p, vitals: newVitals, flagged: abnormal, riskScore: newRisk,
        riskFactors: computeRiskFactors(newVitals, p.severity, p.disease),
        escalationLevel: computeEscalationLevel(newRisk, p.severity) as EscalationLevel,
        vitalHistory: [...p.vitalHistory.slice(-7), { timestamp: Date.now(), heartRate: newVitals.heartRate, oxygen: newVitals.oxygen, bpSystolic: newVitals.bpSystolic }],
      };
    }).sort((a, b) => {
      const order: Record<Severity, number> = { critical: 0, moderate: 1, stable: 2 };
      if (a.flagged !== b.flagged) return a.flagged ? -1 : 1;
      return order[a.severity] - order[b.severity];
    }));
  }, [tick]);

  useEffect(() => {
  const interval = setInterval(() => {
    setPatients((prevPatients) =>
      prevPatients.map((p) => {
        // 🎯 1. VITAL FLUCTUATION
        let newVitals = {
          ...p.vitals,
          heartRate: Math.max(40, Math.min(150, p.vitals.heartRate + (Math.random() * 6 - 3))),
          oxygen: Math.max(80, Math.min(100, p.vitals.oxygen + (Math.random() * 2 - 1))),
          temperature: parseFloat((p.vitals.temperature + (Math.random() * 0.2 - 0.1)).toFixed(1)),
        };

        // ⚠️ RANDOM DETERIORATION (REALISTIC EVENT)
        if (Math.random() < 0.03) {
          newVitals.oxygen -= 5;
          newVitals.heartRate += 10;
        }

        const abnormal = isVitalAbnormal(newVitals);

        // 🧠 2. RISK UPDATE
        const newRisk = computeRiskScore(newVitals, p.severity);
        const newEscalation = computeEscalationLevel(newRisk, p.severity);

        // 📈 3. ECG UPDATE
        const newECG = generateEcgPoints(newVitals.heartRate, abnormal);

        // 🔁 4. TASK AUTO-REGEN
        let updatedTasks = p.tasks;
        if (abnormal && Math.random() < 0.4) {
          updatedTasks = generateTasksForSeverity(p.id, p.severity, true);
        }

        return {
          ...p,
          vitals: {
            ...newVitals,
            ecgPoints: newECG,
            lastChecked: Date.now(),
          },
          flagged: abnormal,
          riskScore: newRisk,
          escalationLevel: newEscalation,
          tasks: updatedTasks,
        };
      })
    );
  }, 2000); // every 2 sec

  return () => clearInterval(interval);
}, []);

useEffect(() => {
  const interval = setInterval(() => {
    setAlerts((prev) => {
      const newAlerts = [...prev];

      patients.forEach((p) => {
        if (p.vitals.oxygen < 88) {
          newAlerts.unshift({
            id: uid(),
            patientId: p.id,
            patientName: p.name,
            type: "vitals",
            message: `Critical oxygen drop (${p.vitals.oxygen}%)`,
            severity: "critical",
            timestamp: Date.now(),
            acknowledged: false,
          });
        }
      });

      return newAlerts.slice(0, 20); // keep last 20
    });
  }, 4000);

  return () => clearInterval(interval);
}, [patients]);

  // Rebuild alerts and escalations on patient changes
  useEffect(() => {
    setAlerts(buildAlerts(patients));
    setEscalations(buildEscalations(patients));
  }, [patients]);

  // Auto task regeneration — when all tasks complete, regenerate
  useEffect(() => {
    setPatients(prev => prev.map(p => {
      const allDone = p.tasks.length > 0 && p.tasks.every(t => t.status === "completed");
      if (!allDone) return p;
      const newTasks = generateTasksForSeverity(p.id, p.severity, isVitalAbnormal(p.vitals));
      return { ...p, tasks: newTasks };
    }));
  }, [tick]);

  const handleCompleteTask = useCallback((patientId: string, taskId: string) => {
    setPatients(prev => prev.map(p => {
      if (p.id !== patientId) return p;
      return { ...p, tasks: p.tasks.map(t => t.id === taskId ? { ...t, status: "completed" as TaskStatus, completedAt: Date.now() } : t) };
    }));
  }, []);

  const handleMarkVitalsChecked = useCallback(async (patientId: string) => {
  const patient = patients.find((p) => p.id === patientId);
  if (!patient) return;

  try {
    await api.updateVitals(patientId, {
      heartRate: patient.vitals.heartRate,
      oxygen: patient.vitals.oxygen,
      bpSystolic: patient.vitals.bpSystolic,
      bpDiastolic: patient.vitals.bpDiastolic,
      temperature: patient.vitals.temperature,
      respiratoryRate: patient.vitals.respiratoryRate,
    });
    await refreshNurseDashboard();
  } catch (err) {
    console.error("Failed to update vitals", err);
  }
}, [patients]);

  const handleCallDoctor = useCallback(async (patient: NursePatient) => {
  try {
    await api.sendAlert({
      source: "nurse",
      patientId: patient.id,
      message: `Nurse requested doctor review for ${patient.name} (${patient.ward}, Bed ${patient.bed})`,
      severity: patient.severity === "critical" ? "critical" : "medium",
    });
    await refreshNurseDashboard();
  } catch (err) {
    console.error("Failed to call doctor", err);
  }
}, [nurseName]);

  const handleRegenTasks = useCallback((patientId: string) => {
    setPatients(prev => prev.map(p => {
      if (p.id !== patientId) return p;
      const newTasks = generateTasksForSeverity(p.id, p.severity, isVitalAbnormal(p.vitals));
      return { ...p, tasks: newTasks };
    }));
  }, []);

  const handleAcknowledgeAlert = useCallback((alertId: string) => {
    setAlerts(prev => prev.map(a => a.id === alertId ? { ...a, acknowledged: true } : a));
  }, []);

  const handleAcknowledgeEscalation = useCallback((escId: string) => {
    setEscalations(prev => prev.map(e => e.id === escId ? { ...e, status: e.status === "open" ? "acknowledged" : "resolved" } : e));
  }, []);

  const unackedAlerts = alerts.filter(a => !a.acknowledged).length;

  if (loading && patients.length === 0) {
  return (
    <div className="min-h-screen flex items-center justify-center">
      Loading Nurse Dashboard...
    </div>
  );
}

  return (
    <div className="flex h-screen overflow-hidden" style={{ background: "linear-gradient(135deg, #f0f4ff 0%, #fafbff 50%, #f5f0ff 100%)" }}>
      <Sidebar active={view} onChange={setView} alertCount={unackedAlerts} collapsed={sidebarCollapsed} onToggle={() => setSidebarCollapsed(c => !c)} />
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
        <DashboardHeader patients={patients} alerts={alerts} view={view} />
        <main className="flex-1 overflow-y-auto p-5">
          <AnimatePresence mode="wait">
            {view === "overview" && <OverviewView key="overview" patients={patients} alerts={alerts} />}
            {view === "patients" && (
              <PatientCareView key="patients" patients={patients} selectedId={selectedId} setSelectedId={setSelectedId}
                filter={filter} setFilter={setFilter} handleCompleteTask={handleCompleteTask}
                handleMarkVitalsChecked={handleMarkVitalsChecked} handleCallDoctor={handleCallDoctor} handleRegenTasks={handleRegenTasks} />
            )}
            {view === "handover" && <HandoverView key="handover" handovers={handovers} patients={patients} />}
            {view === "escalation" && <EscalationView key="escalation" patients={patients} escalations={escalations} onAcknowledge={handleAcknowledgeEscalation} />}
            {view === "alerts" && <AlertsView key="alerts" alerts={alerts} patients={patients} onAcknowledge={handleAcknowledgeAlert} />}
            {view === "history" && <HistoryView key="history" patients={patients} selectedId={selectedId} setSelectedId={setSelectedId} />}
            {view === "analytics" && <AnalyticsView key="analytics" patients={patients} />}
          </AnimatePresence>
        </main>
      </div>
    </div>
  );
}